name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:oracular

    steps:
    - uses: actions/checkout@v2

    - name: Setup
      run: apt-get -q -y update && apt-get -q -y install git gcc cmake cppcheck libcmocka-dev

    - name: Instal Dart
      run: |
        apt-get update -qy && apt-get install -qy apt-transport-https wget
        wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg  --dearmor -o /usr/share/keyrings/dart.gpg
        echo 'deb [signed-by=/usr/share/keyrings/dart.gpg arch=amd64] https://storage.googleapis.com/download.dartlang.org/linux/debian stable main' |  tee /etc/apt/sources.list.d/dart_stable.list
        apt-get update -qy && apt-get install -qy dart

    - name: Configure
      # Configure CMake in a 'build' subdirectory.
      run: mkdir build && cd build && cmake .. 

    - name: Build
      # Build your program with the given configuration
      working-directory: ${{github.workspace}}/build
      run: make

    - name: Tests
      # Execute tests defined by the CMake configuration.
      working-directory: ${{github.workspace}}/build
      run: make tests

    - name: Integration tests
      working-directory: ${{github.workspace}}
      run: dart tool/bin/test.dart -i build/src/pit

    - name: Rsync
      if: ${{ github.ref == 'refs/heads/main' }} && ${{ github.event_name == 'push' }}
      run: apt-get update && apt-get install -y rsync
