name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:oracular

    steps:
    - uses: actions/checkout@v2

    - name: Setup
      run: apt-get -q -y update && apt-get -q -y install git gcc cmake cppcheck libcmocka-dev

    - name: Configure
      # Configure CMake in a 'build' subdirectory.
      run: mkdir build && cd build && cmake .. 

    - name: Build
      # Build your program with the given configuration
      working-directory: ${{github.workspace}}/build
      run: make

    - name: Tests
      # Execute tests defined by the CMake configuration.
      working-directory: ${{github.workspace}}/build
      run: make tests

    - name: Integration tests
      working-directory: ${{github.workspace}}
      run: dart tool/bin/test.dart -i build/src/pit
      
    - name: Rsync
      if: ${{ github.ref == 'refs/heads/main' }} && ${{ github.event_name == 'push' }}
      run: apt-get update && apt-get install -y rsync
