name: Docker Container

# The CI.yml action depends on a custom container with cmake, cmocka and so on.
# It is build here whenever the Dockerfile changes.

on:
  push:
    paths:
      - '.devcontainer/Dockerfile'
      - '.github/workflows/container.yml'
    branches: main
  pull_request:
    paths:
      - '.devcontainer/Dockerfile'
      - '.github/workflows/container.yml'
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1